//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_SegurosEntities : DbContext
    {
        public DB_SegurosEntities()
            : base("name=DB_SegurosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tb_Afp> tb_Afp { get; set; }
        public virtual DbSet<tb_BeneficiarioPoliza> tb_BeneficiarioPoliza { get; set; }
        public virtual DbSet<tb_CiaSeguro> tb_CiaSeguro { get; set; }
        public virtual DbSet<tb_Cobertura> tb_Cobertura { get; set; }
        public virtual DbSet<tb_DocumentoIdentidad> tb_DocumentoIdentidad { get; set; }
        public virtual DbSet<tb_Estado> tb_Estado { get; set; }
        public virtual DbSet<tb_Modalidad> tb_Modalidad { get; set; }
        public virtual DbSet<tb_Moneda> tb_Moneda { get; set; }
        public virtual DbSet<tb_Persona> tb_Persona { get; set; }
        public virtual DbSet<tb_Poliza> tb_Poliza { get; set; }
        public virtual DbSet<tb_Relacion> tb_Relacion { get; set; }
        public virtual DbSet<tb_Salud> tb_Salud { get; set; }
        public virtual DbSet<tb_Sexo> tb_Sexo { get; set; }
        public virtual DbSet<tb_SolicitudCotizacion> tb_SolicitudCotizacion { get; set; }
        public virtual DbSet<tb_TipoPersona> tb_TipoPersona { get; set; }
    }
}
