//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BeneficiarioPoliza
    {
        public int CodigoBeneficiario { get; set; }
        public int CodigoPoliza { get; set; }
        public int CodigoPersona { get; set; }
        public int CodigoRelacion { get; set; }
        public int CodigoTipoPersona { get; set; }
        public int CodigoEstado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual tb_Estado tb_Estado { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
        public virtual tb_Poliza tb_Poliza { get; set; }
        public virtual tb_Relacion tb_Relacion { get; set; }
        public virtual tb_TipoPersona tb_TipoPersona { get; set; }
    }
}
