//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Poliza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Poliza()
        {
            this.tb_BeneficiarioPoliza = new HashSet<tb_BeneficiarioPoliza>();
        }
    
        public int CodigoPoliza { get; set; }
        public int NumeroPoliza { get; set; }
        public System.DateTime FechaDevengue { get; set; }
        public System.DateTime FechaDevengueSolicitud { get; set; }
        public System.DateTime FechaNotificacion { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public decimal PrimaUnica { get; set; }
        public int PeriodoDiferido { get; set; }
        public int PeriodoGarantizado { get; set; }
        public decimal PorcentajaGarantizado { get; set; }
        public string Gratificacion { get; set; }
        public string DerechoCrecer { get; set; }
        public decimal PensionDevengue { get; set; }
        public decimal CIC { get; set; }
        public int CodigoPersona { get; set; }
        public int CodigoAfp { get; set; }
        public int CodigoEstado { get; set; }
        public int CodigoMoneda { get; set; }
        public int CodigoCobertura { get; set; }
        public int CodigoModalidad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual tb_Afp tb_Afp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BeneficiarioPoliza> tb_BeneficiarioPoliza { get; set; }
        public virtual tb_Cobertura tb_Cobertura { get; set; }
        public virtual tb_Estado tb_Estado { get; set; }
        public virtual tb_Modalidad tb_Modalidad { get; set; }
        public virtual tb_Moneda tb_Moneda { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
