//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Persona()
        {
            this.tb_BeneficiarioPoliza = new HashSet<tb_BeneficiarioPoliza>();
            this.tb_Poliza = new HashSet<tb_Poliza>();
            this.tb_SolicitudCotizacion = new HashSet<tb_SolicitudCotizacion>();
        }
    
        public int CodigoPersona { get; set; }
        public string CUSSPP { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public System.DateTime FechaFallecimiento { get; set; }
        public int CodigoSexo { get; set; }
        public int CodigoDocumentoIdentidad { get; set; }
        public int CodigoSalud { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_BeneficiarioPoliza> tb_BeneficiarioPoliza { get; set; }
        public virtual tb_DocumentoIdentidad tb_DocumentoIdentidad { get; set; }
        public virtual tb_Salud tb_Salud { get; set; }
        public virtual tb_Sexo tb_Sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Poliza> tb_Poliza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_SolicitudCotizacion> tb_SolicitudCotizacion { get; set; }
    }
}
