//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_SolicitudCotizacion
    {
        public int CodigoSolicitud { get; set; }
        public decimal PrimaUnica { get; set; }
        public decimal TasaVenta { get; set; }
        public decimal CIC { get; set; }
        public int CodigoPersona { get; set; }
        public int CodigoAfp { get; set; }
        public int CodigoCiaSeguro { get; set; }
        public int CodigoModalidad { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaModificacion { get; set; }
    
        public virtual tb_Afp tb_Afp { get; set; }
        public virtual tb_CiaSeguro tb_CiaSeguro { get; set; }
        public virtual tb_Modalidad tb_Modalidad { get; set; }
        public virtual tb_Persona tb_Persona { get; set; }
    }
}
